{% set name = "moscot" %}
{% set version = "0.4.1" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/moscot-{{ version }}.tar.gz
  sha256: 4962e9b017f8816ac8e08eabec9a9e150698c363e70966b8b50fd14389e532c5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools_scm
  run:
    - python >={{ python_min }}
    - numpy >=1.20.0
    - scipy >=1.7.0
    - pandas >=2.0.1
    - networkx >=2.6.3
    - matplotlib-base >=3.5.0
    - anndata >=0.9.1
    - scanpy >=1.9.3
    - wrapt >=1.13.2
    - ott-jax >=0.5.0
    - cloudpickle >=2.2.0
    - rich >=13.5
    - docstring-inheritance >=2.0.0
    - mudata >=0.2.2
    - flax >=0.10.2
    - optax >=0.2.4
    - diffrax >=0.6.1

test:
  requires:
    - python {{ python_min }}
  imports:
    - moscot

about:
  home: https://github.com/theislab/moscot
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Multi-omic single-cell optimal transport
  description: |
    A scalable framework for optimal transport applications in single-cell genomics.
  doc_url: https://moscot.readthedocs.io
  dev_url: https://github.com/theislab/moscot

extra:
  recipe-maintainers:
    - michalk8
    - MUCDK
    - giovp
    - selmanozleyen
