{% set name = "moscot" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/moscot-{{ version }}.tar.gz
  sha256: e6aa84558408678179926c5890e0e9536d58815309fc61a55633cca13eca09b1

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools_scm
  run:
    - python >=3.8
    - numpy >=1.20.0
    - scipy >=1.7.0
    - pandas >=1.4.0
    - networkx >=2.6.3
    - matplotlib-base >=3.5.0
    - anndata >=0.8.0
    - scanpy >=1.9.3
    - wrapt >=1.13.2
    - docrep >=0.3.2
    - ott-jax >=0.4.0
    - cloudpickle >=2.2.0

test:
  imports:
    - moscot
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/theislab/moscot
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Multi-omic single-cell optimal transport
  description: |
    A scalable framework for optimal transport applications in single-cell genomics.
  doc_url: https://moscot.readthedocs.io
  dev_url: https://github.com/theislab/moscot

extra:
  recipe-maintainers:
    - michalk8
    - MUCDK
    - giovp
