{% set name = "moscot" %}
{% set version = "0.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/moscot-{{ version }}.tar.gz
  sha256: 0158a2f7c1754ef977359f22f8406c2a2f45474d2a3171ed85394253fb3a80a3

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools_scm
  run:
    - python >=3.8
    - numpy >=1.20.0
    - scipy >=1.7.0
    - pandas >=2.0.1
    - networkx >=2.6.3
    - matplotlib-base >=3.5.0
    - anndata >=0.9.1
    - scanpy >=1.9.3
    - wrapt >=1.13.2
    - ott-jax >=0.4.4
    - cloudpickle >=2.2.0
    - rich >=13.5

test:
  imports:
    - moscot
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/theislab/moscot
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Multi-omic single-cell optimal transport
  description: |
    A scalable framework for optimal transport applications in single-cell genomics.
  doc_url: https://moscot.readthedocs.io
  dev_url: https://github.com/theislab/moscot

extra:
  recipe-maintainers:
    - michalk8
    - MUCDK
    - giovp
