{% set name = "moscot" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/moscot-{{ version }}.tar.gz
  sha256: f39de871356877b26875df318051b3efcdbc41a3a2df54a0479b4a0b29fc8473

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.10
    - pip
    - setuptools_scm
  run:
    - python >=3.10
    - numpy >=1.20.0
    - scipy >=1.7.0
    - pandas >=2.0.1
    - networkx >=2.6.3
    - matplotlib-base >=3.5.0
    - anndata >=0.9.1
    - scanpy >=1.9.3
    - wrapt >=1.13.2
    - ott-jax >=0.5.0
    - cloudpickle >=2.2.0
    - rich >=13.5
    - docstring-inheritance >=2.0.0
    - mudata >=0.2.2
    - flax >=0.10.2
    - optax >=0.2.4
    - diffrax >=0.6.1

test:
  imports:
    - moscot
  # TODO(michalk8): re-enable once https://github.com/pypa/pip/issues/11157 is merged
  # or the false positives are resolved in moscot/ott-jax/umap-learn

  # requires:
  #   - pip
  # commands:
  #   - pip check

about:
  home: https://github.com/theislab/moscot
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Multi-omic single-cell optimal transport
  description: |
    A scalable framework for optimal transport applications in single-cell genomics.
  doc_url: https://moscot.readthedocs.io
  dev_url: https://github.com/theislab/moscot

extra:
  recipe-maintainers:
    - michalk8
    - MUCDK
    - giovp
    - selmanozleyen
