{% set name = "moscot" %}
{% set version = "0.3.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/moscot-{{ version }}.tar.gz
  sha256: 438b9ee5a619b21e554573bd61d30d2db331a493cab875289fceb09952a711e7

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools_scm
  run:
    - python >={{ python_min }}
    - numpy >=1.20.0
    - scipy >=1.7.0
    - pandas >=2.0.1
    - networkx >=2.6.3
    - matplotlib-base >=3.5.0
    - anndata >=0.9.1
    - scanpy >=1.9.3
    - wrapt >=1.13.2
    - ott-jax >=0.4.4
    - cloudpickle >=2.2.0
    - rich >=13.5

test:
  requires:
    - python {{ python_min }}
  imports:
    - moscot
  # TODO(michalk8): re-enable once https://github.com/pypa/pip/issues/11157 is merged
  # or the false positives are resolved in moscot/ott-jax/umap-learn

  # requires:
  #   - pip
  # commands:
  #   - pip check

about:
  home: https://github.com/theislab/moscot
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Multi-omic single-cell optimal transport
  description: |
    A scalable framework for optimal transport applications in single-cell genomics.
  doc_url: https://moscot.readthedocs.io
  dev_url: https://github.com/theislab/moscot

extra:
  recipe-maintainers:
    - michalk8
    - MUCDK
    - giovp
